export const consts = {
  //Mutations
  SET_VALUE: 'setValue',
  SET_VAL_MESSAGE: 'setValMessage',
  SET_VAL_NAME: 'setValName',
  SET_VAL_CALENDAR: 'setValCalendar',
  SET_VAL_HOUR: 'setValHour',
  SET_VAL_MINUTE: 'setValMinute',
  SET_VAL_DAYS: 'setValDays',
  SET_STATE: 'setState',
  SET_STATE_WIDGETS: 'setStateWidgets',
  SET_STATE_DIALOG: 'setStateDialog',
  SET_STATE_BOT_BUSY: 'setStateBotBusy',
  SET_STATE_THEME: 'setStateTheme',
  SET_MSGS_LIST: 'setMsgsList',
  SET_LOADING: 'setLoading',
  LOADING_MSGS_LIST: 'loadingMsgsList',
  HIDE_OPTIONS: 'hideOptions',
  UPDATE_CHAT: 'updateChat',
  //Actions
  ACT_LOADING: 'actLoading',

  //Data states
  ARR_WIDGETS: [
    { name: 'Календарь', icon: '$iconCalendar' },
    { name: 'Будильник', icon: '$iconClock' },
    { name: 'Погода', icon: '$iconWeather' },
    { name: 'Доставка', icon: '$iconNoodles' },
    { name: 'Что умеешь?', icon: '$iconScriptText' },
  ],
  ARR_CLOCK: [
    'Понедельник',
    'Вторник',
    'Среда',
    'Четверг',
    'Пятница',
    'Суббота',
    'Воскресенье',
  ],
  ARR_WEATHER: [
    {
      degree: '-11',
      icon: '$iconWeatherSnowyHeavy',
      day: 'Четверг',
      date: '14.12',
      wind: {
        value: '7',
        unit: 'м/с',
        icon: '$iconWeatherWindy',
        text: 'Порывы ветра',
      },
      water: {
        value: '48',
        unit: '%',
        icon: '$iconWeatherPouring',
        text: 'Влажность',
      },
      disc: 'Пасмурно, сильный снег',
    },
    {
      degree: '-13',
      icon: '$iconWeatherPartlySnowyRainy',
      day: 'Пт',
      date: '15.12',
      disc: 'Облачно, небольшой снег с дождём',
    },
    {
      degree: '-10',
      icon: '$iconWeatherPartlySnowy',
      day: 'Сб',
      date: '16.12',
      disc: 'Облачно, небольшой снег',
    },
    {
      degree: '-12',
      icon: '$iconWeatherPartlyCloudy',
      day: 'Вс',
      date: '17.12',
      disc: 'Облачно',
    },
    {
      degree: '-17',
      icon: '$iconWeatherSnowyRainy',
      day: 'Пн',
      date: '18.12',
      disc: 'Пасмурно, небольшой снег с дождём',
    },
    {
      degree: '-19',
      icon: '$iconWeatherSnowy',
      day: 'Вт',
      date: '19.12',
      disc: 'Облачно, небольшой снег',
    },
    {
      degree: '-22',
      icon: '$iconWeatherSnowy',
      day: 'Ср',
      date: '20.12',
      disc: 'Облачно, небольшой снег',
    },
    {
      degree: '-25',
      icon: '$iconWeatherSnowyHeavy',
      day: 'Чт',
      date: '21.12',
      disc: 'Пасмурно, небольшой снег с дождём',
    },
    {
      degree: '-19',
      icon: '$iconWeatherPartlySnowy',
      day: 'Пт',
      date: '22.12',
      disc: 'Облачно, небольшой снег',
    },
    {
      degree: '-14',
      icon: '$iconWeatherPartlySnowyRainy',
      day: 'Сб',
      date: '23.12',
      disc: 'Облачно, небольшой снег с дождём',
    },
  ],
  //Commands
  COMMAND_HELLO: {
    value:
      'Приветствую тебя! Меня зовут <span class="colorSecondary">Чатти</span>!',
    name: 'Приветствие',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Имя',
    show: true,
  },
  COMMAND_NAME: {
    value:
      'Как мне к тебе обращаться? Пожалуйста, напиши своё <span class="colorSecondary">имя</span> для <span class="colorSecondary">Чатти</span>.',
    name: 'Имя',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_GUEST_NAME: {
    value:
      'Очень приятно познакомиться <span class="colorSecondary">Первопроходец</span>! Чем я могу тебе помочь?',
    name: 'ИмяГостя',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Опции',
    show: true,
  },
  COMMAND_OPTIONS: {
    value: [
      { name: 'Календарь', command: 'Календарь' },
      { name: 'Будильник', command: 'Будильник' },
      { name: 'Погода', command: 'Погода' },
      { name: 'Доставка', command: 'Доставка' },
      { name: 'Имя', command: 'Имя' },
    ],
    name: 'Опции',
    type: 'options',
    moreMsg: false,
    show: true,
    countHide: 1,
  },
  COMMAND_UNKNOWN: {
    value:
      '<span class="colorSecondary">Чатти</span> не понимает тебя, пожалуйста выбери одну из команд ниже.',
    name: 'Неизвестная',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Опции',
    show: true,
  },
  COMMAND_CALENDAR: {
    value:
      'Календарь со всеми предстающими событиями. Желаете создать <span class="colorSecondary">уведомление</span>?',
    name: 'Календарь',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Выбрать уведомление',
    show: true,
  },
  COMMAND_CHOICE_NOTIFICATION: {
    value: 'Выбрать уведомление',
    name: 'Выбрать уведомление',
    type: 'widget',
    moreMsg: true,
    nextMsg: 'Уведомление',
    show: true,
  },
  COMMAND_NOTIFICATION: {
    value: [
      { name: 'Создать', command: 'Создать' },
      { name: 'Отменить', command: 'Отменить' },
    ],
    name: 'Уведомление',
    type: 'options',
    moreMsg: false,
    show: true,
    countHide: 2,
  },
  COMMAND_NOTIFICATION_CONFIRM: {
    value: 'Уведомление успешно создано!',
    name: 'Создать',
    type: 'msgPers',
    moreMsg: false,
    show: true,
  },
  COMMAND_NOTIFICATION_CANCEL: {
    value: 'Создание уведомления отменено!',
    name: 'Отменить',
    type: 'msgPers',
    moreMsg: false,
    show: true,
  },
  COMMAND_CLOCK: {
    value:
      'Установите желаемое <span class="colorSecondary">время</span> и <span class="colorSecondary">день недели</span> для будильника.',
    name: 'Будильник',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Изменить будильник',
    show: true,
  },
  COMMAND_CHANGE_CLOCK: {
    value: 'Изменить будильник',
    name: 'Изменить будильник',
    type: 'widget',
    moreMsg: true,
    nextMsg: 'Время будильника',
    show: true,
  },
  COMMAND_CLOCK_TIME: {
    value: [
      { name: 'Установить', command: 'Установить' },
      { name: 'Отключить', command: 'Отключить' },
    ],
    name: 'Время будильника',
    type: 'options',
    moreMsg: false,
    show: true,
    countHide: 2,
  },
  COMMAND_CLOCK_INSTALL: {
    value: 'Будильник успешно установлен!',
    name: 'Установить',
    type: 'msgPers',
    moreMsg: false,
    show: true,
  },
  COMMAND_CLOCK_UNPLUG: {
    value: 'Будильник отключен!',
    name: 'Отключить',
    type: 'msgPers',
    moreMsg: false,
    show: true,
  },
  COMMAND_WEATHER: {
    value:
      'Прогноз погоды в Москве на ближайшие <span class="colorSecondary">10 дней</span>.',
    name: 'Погода',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Показать погоду',
    show: true,
  },
  COMMAND_SHOW_WEATHER: {
    value: 'Показать погоду',
    name: 'Показать погоду',
    type: 'widget',
    moreMsg: false,
    show: true,
  },
  COMMAND_DELIVERY: {
    value:
      'Что желаете заказать? <span class="colorSecondary">Чатти</span> составил для вас список самых вкусных блюд!',
    name: 'Доставка',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Список еды',
    show: true,
  },
  COMMAND_LIST_FOOD: {
    value: [
      { name: 'Чан Рамен', command: 'Чан Рамен' },
      { name: 'Пицца с ананасами', command: 'Пицца с ананасами' },
      { name: 'Бургер с говядиной', command: 'Бургер с говядиной' },
      { name: 'Вок с морепродуктами', command: 'Вок с морепродуктами' },
      { name: 'Деревенская картошка', command: 'Деревенская картошка' },
      { name: 'Яндекс лавка', command: 'Яндекс лавка' },
    ],
    name: 'Список еды',
    type: 'options',
    moreMsg: false,
    show: true,
    countHide: 1,
  },
  COMMAND_FOOD_PIZZA: {
    value:
      'Ты заказал <span class="colorSecondary">пиццу с ананасами</span>! Доставка ориентировочно займет <span class="colorSecondary">25 минут</span>. Приятного аппетита!',
    name: 'Пицца с ананасами',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_FOOD_BURGER: {
    value:
      'Сочный вкусный <span class="colorSecondary">бургер</span>  с говядиной от <span class="colorSecondary">Burger King</span>  уже мчится к тебе! Заказ готовится, как только его передадут курьеру, <span class="colorSecondary">Чатти</span> сообщит тебе.',
    name: 'Бургер с говядиной',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_FOOD_WOK: {
    value:
      'Спасибо за заказ! Повора уже начали готовить <span class="colorSecondary">Вок с морепродуктами</span>. Ожидайте курьера в течение 35 минут! Хорошего дня, ваш <span class="colorSecondary">Чатти</span>!',
    name: 'Вок с морепродуктами',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_FOOD_POTATOES: {
    value:
      'Горячая, вкусная и нежная картошечка из <span class="colorSecondary">Burger King</span> спешит к тебе. Заказ готовится, как только его передадут курьеру, <span class="colorSecondary">Чатти</span> сообщит тебе.',
    name: 'Деревенская картошка',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_FOOD_PRODUCTS: {
    value:
      'Самые свежие и лучшие продукты прямиком из <span class="colorSecondary">Яндекс лавки</span>. Курьер собирает ваш заказ, с наилучшими пожеланиями ваш <span class="colorSecondary">Чатти</span>!',
    name: 'Яндекс лавка',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_FOOD_RAMEN: {
    value:
      'Самый вкусный <span class="colorSecondary">Чан Рамен</span> в сырном бульоне. Заказ готовится и скоро будет у вас, приятного аппетита!',
    name: 'Чан Рамен',
    type: 'msg',
    moreMsg: false,
    show: true,
  },
  COMMAND_ABOUT: {
    value:
      '<span class="colorSecondary">Чатти</span> очень умный! Выберите желаемый вариант!',
    name: 'Что умеешь?',
    type: 'msg',
    moreMsg: true,
    nextMsg: 'Опции',
    show: true,
  },
}
